# Generated by Django 6.0.5 on 2026-05-29 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('active', 'Active Lease'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True, help_text="Tenant's application message")),
                ('move_in_date', models.DateField()),
                ('lease_term_months', models.IntegerField()),
                ('expected_move_out_date', models.DateField(blank=True, null=True)),
                ('number_of_occupants', models.IntegerField(default=1)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('approval_message', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('rejected_date', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bookings',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaseAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_signature', 'Pending Signature'), ('signed', 'Signed'), ('terminated', 'Terminated')], default='draft', max_length=20)),
                ('contract_number', models.CharField(max_length=100, unique=True)),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=15)),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('terms', models.TextField()),
                ('special_conditions', models.TextField(blank=True)),
                ('document_file', models.FileField(blank=True, null=True, upload_to='lease_agreements/')),
                ('landlord_signed', models.BooleanField(default=False)),
                ('landlord_signature_date', models.DateTimeField(blank=True, null=True)),
                ('tenant_signed', models.BooleanField(default=False)),
                ('tenant_signature_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'lease_agreements',
            },
        ),
        migrations.CreateModel(
            name='PropertyVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('confirmed_by_landlord', models.BooleanField(default=False)),
                ('landlord_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'property_visits',
                'ordering': ['-scheduled_date'],
            },
        ),
    ]
