# Generated by Django 6.0.5 on 2026-05-29 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings_app', '0001_initial'),
        ('payments_app', '0001_initial'),
        ('properties_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='properties_app.property'),
        ),
        migrations.AddField(
            model_name='payment',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bookings_app.booking'),
        ),
        migrations.AddField(
            model_name='payment',
            name='rental_property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties_app.property'),
        ),
    ]
