# Generated by Django 6.0.5 on 2026-05-29 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('listing_type', models.CharField(choices=[('rent', 'For Rent'), ('sale', 'For Sale'), ('both', 'For Rent & Sale')], max_length=20)),
                ('number_of_rooms', models.IntegerField()),
                ('number_of_bathrooms', models.IntegerField()),
                ('square_meters', models.FloatField(blank=True, null=True)),
                ('year_built', models.IntegerField(blank=True, null=True)),
                ('has_kitchen', models.BooleanField(default=True)),
                ('has_water', models.BooleanField(default=True)),
                ('has_electricity', models.BooleanField(default=True)),
                ('furnished', models.BooleanField(default=False)),
                ('has_parking', models.BooleanField(default=False)),
                ('has_garden', models.BooleanField(default=False)),
                ('has_balcony', models.BooleanField(default=False)),
                ('allows_pets', models.BooleanField(default=False)),
                ('rent_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('deposit_required', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('service_charges', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('country', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('cell', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=255)),
                ('street_address', models.CharField(max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Under Maintenance'), ('inactive', 'Inactive')], default='available', max_length=20)),
                ('available_from', models.DateField()),
                ('lease_term_months', models.IntegerField(blank=True, null=True)),
                ('security_provider', models.CharField(blank=True, max_length=255, null=True)),
                ('boundary_wall', models.BooleanField(default=False)),
                ('contact_method', models.CharField(choices=[('direct', 'Direct Contact'), ('platform', 'Platform Only'), ('both', 'Both')], default='both', max_length=50)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('total_views', models.IntegerField(default=0)),
                ('total_applications', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'db_table': 'properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Property Amenities',
                'db_table': 'property_amenities',
            },
        ),
        migrations.CreateModel(
            name='PropertyAmenityLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'property_amenity_links',
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_images/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('is_main_image', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Property Images',
                'db_table': 'property_images',
            },
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Property Types',
                'db_table': 'property_types',
            },
        ),
        migrations.CreateModel(
            name='SavedProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'saved_properties',
            },
        ),
    ]
